# Auto-generated by Stage A Topology Generator
# Generated at: <DIVO.env.pusht.llm_topology_generator.LLMTopologyGenerator object at 0x788021530640>

def generate_obstacles(tblock_pose: np.ndarray, num_obstacles: int) -> list:
    obstacles = []
    tx, ty, ttheta = tblock_pose[0], tblock_pose[1], tblock_pose[2]
    goal = np.array([0.0, 0.0])
    start = np.array([tx, ty])
    v = goal - start
    v_norm = np.linalg.norm(v)
    if v_norm > 1e-6:
        dir_vec = v / v_norm
        perp_vec = np.array([-dir_vec[1], dir_vec[0]])
    else:
        dir_vec = np.array([1.0, 0.0])
        perp_vec = np.array([0.0, 1.0])
    corridor_width = 0.04
    for _ in range(num_obstacles):
        found = False
        for attempt in range(50):
            if np.random.rand() < 0.6:
                t_along = np.random.uniform(0.35, 0.8)
                offset_sign = 1.0 if np.random.rand() < 0.5 else -1.0
                offset = np.random.uniform(0.08, 0.13) * offset_sign
                cand = start + t_along * v + offset * perp_vec
            else:
                edge_choice = np.random.randint(0, 4)
                if edge_choice == 0:
                    cand = np.array([np.random.uniform(-0.17, -0.13), np.random.uniform(-0.17, 0.17)])
                elif edge_choice == 1:
                    cand = np.array([np.random.uniform(0.13, 0.17), np.random.uniform(-0.17, 0.17)])
                elif edge_choice == 2:
                    cand = np.array([np.random.uniform(-0.17, 0.17), np.random.uniform(-0.17, -0.13)])
                else:
                    cand = np.array([np.random.uniform(-0.17, 0.17), np.random.uniform(0.13, 0.17)])
                cand += np.random.uniform(-0.01, 0.01, size=2)
            if not (-0.19 <= cand[0] <= 0.19 and -0.19 <= cand[1] <= 0.19):
                continue
            if not is_safe(cand[0], cand[1], tx, ty, ttheta):
                continue
            vec_to_start = cand - start
            vec_to_goal = cand - goal
            if np.dot(vec_to_start, dir_vec) >= 0 and np.dot(vec_to_goal, -dir_vec) >= 0:
                d_seg = np.abs(np.cross(v, cand - start)) / v_norm if v_norm > 1e-6 else np.linalg.norm(cand - start)
                if d_seg < corridor_width:
                    continue
            conflict = False
            for obs in obstacles:
                if np.linalg.norm(cand - np.array([obs['x'], obs['y']])) <= 0.03:
                    conflict = True
                    break
            if conflict:
                continue
            found = True
            purpose = "side_pressure" if np.random.rand() < 0.5 else "edge_presence"
            obstacles.append({'x': float(cand[0]), 'y': float(cand[1]), 'purpose': purpose})
            break
    if num_obstacles > 0 and len(obstacles) == 0:
        while True:
            corner_choice = np.random.randint(0, 4)
            if corner_choice == 0:
                cand = np.array([np.random.uniform(-0.19, -0.15), np.random.uniform(-0.19, -0.15)])
            elif corner_choice == 1:
                cand = np.array([np.random.uniform(0.15, 0.19), np.random.uniform(-0.19, -0.15)])
            elif corner_choice == 2:
                cand = np.array([np.random.uniform(-0.19, -0.15), np.random.uniform(0.15, 0.19)])
            else:
                cand = np.array([np.random.uniform(0.15, 0.19), np.random.uniform(0.15, 0.19)])
            if not is_safe(cand[0], cand[1], tx, ty, ttheta):
                continue
            if -0.19 <= cand[0] <= 0.19 and -0.19 <= cand[1] <= 0.19:
                obstacles.append({'x': float(cand[0]), 'y': float(cand[1]), 'purpose': 'corner_hint'})
                break
    return obstacles