#!/usr/bin/env python3
"""测试 Stage A Prompt 生成"""

import os
import sys
import numpy as np
from DIVO.env.pusht.llm_topology_generator import (
    LLMTopologyGenerator,
    build_phase0_prompt_stage_a
)

def main():
    print("=" * 80)
    print("测试 Stage A Topology Generator")
    print("=" * 80)
    
    # 1. 检查 API key
    api_key = os.getenv("DEEPSEEK_API_KEY")
    if not api_key:
        print("❌ 错误: 未找到 DEEPSEEK_API_KEY 环境变量")
        print("请设置: export DEEPSEEK_API_KEY='your-api-key'")
        sys.exit(1)
    
    print(f"✓ 找到 API key: {api_key[:10]}...")
    
    # 2. 初始化生成器
    print("\n初始化 LLM Topology Generator...")
    generator = LLMTopologyGenerator(
        api_type="deepseek",
        model="deepseek-chat",
        api_key=api_key
    )
    print("✓ 生成器初始化成功")
    
    # 3. 构建 prompt（使用独立函数）
    print("\n" + "=" * 80)
    print("构建 Stage A Prompt")
    print("=" * 80)
    # 使用示例 T-block 位置
    tblock_pose = np.array([0.15, 0.15, np.pi/4])
    prompt = build_phase0_prompt_stage_a(tblock_pose, num_obstacles=2)
    print(prompt)
    
    # 4. 调用 LLM API 生成代码
    print("\n" + "=" * 80)
    print("调用 LLM API 生成拓扑生成器代码...")
    print("=" * 80)
    try:
        response = generator._call_llm(prompt)
        print("\n✓ LLM 响应:")
        print("-" * 80)
        print(response)
    except Exception as e:
        print(f"\n❌ API 调用失败: {e}")
        sys.exit(1)
    
    # 5. 提取函数代码
    print("\n" + "=" * 80)
    print("提取生成的函数代码")
    print("=" * 80)
    try:
        code = generator._extract_code(response)
        print(code)
        print("\n✓ 代码提取成功")
        print(f"代码长度: {len(code)} 字符")
    except Exception as e:
        print(f"\n❌ 代码提取失败: {e}")
        sys.exit(1)
    
    # 6. 可选：保存到文件
    output_file = "generated_topology_function.py"
    with open(output_file, "w") as f:
        f.write("# Auto-generated by Stage A Topology Generator\n")
        f.write("# Generated at: " + str(generator) + "\n\n")
        f.write(code)
    print(f"\n✓ 代码已保存到: {output_file}")
    
    print("\n" + "=" * 80)
    print("测试完成")
    print("=" * 80)

if __name__ == "__main__":
    main()
